version: '3'

services:

  mongodb:  
    build: .
    image: dannyben/alpine-mongo
    ports: ["27017:27017"]

  client:  
    image: dannyben/alpine-mongo
    command: mongo mongodb://mongodb:27017
    depends_on: [mongodb]

  bash:  
    image: dannyben/alpine-mongo
    command: bash
    depends_on: [mongodb]
